### ISSUE TITLE
Support multiple compiler versions via docker image tags

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/cachalot#3]
https://github.com/sociomantic-tsunami/ocean/pull/102#discussion_r115117973

Core issue is that eventually we will need to test at least ocean with multiple compiler version (for example, "current dmd1" + "current dmd-transitional" + "upcoming dmd-transitional" + "vanilla upstream") while using pre-built/cached toolchain docker images as much as possible.

Additionally, it would make travis report (https://travis-ci.org/sociomantic-tsunami/ocean/builds/229419888) much readable if matrix was to show actual compiler versions as opposed to abstract `dmd1`/`dmd-transitional`.

The approach I am envisioning right now would be to considerably change docker image hierarchy and the way D compiler is installed inside. Right now we have single `dlang` image with both compilers and ubuntu release tags. Instead I would introduce `base-xenial` and `base-precise` images and generate `dlang-xenial:v1.080.0` and `dlang-precise:v2.070.2.s10` from it with `latest` tag matching our current apt-provided versions. What is more important, internally I'd provide single `dmd` link to whatever compiler is used not matter the version, simplifying further scripting.

**Comment by leandro-lucarella-sociomantic** [comment]
For this approach we will need to have one Dockerfile per combination of [dmd,ubuntu distro] (because we can't use docker build arguments for the `FROM` line, and the compiler version will have to be specified in the `FROM` line this way) so it seems overkill.

Another option would be to have some script to build a Dockerfile dynamically generated but we already went that route and I prefer not to go there again.

I think this is a major problem for this approach. We could add a feature request to docker to allow using build arguments in the `FROM` line and wait a few years :P

**Comment by leandro-lucarella-sociomantic** [comment]
I've been playing around a bit with this idea and how to move forward with build-matrixes and I think the best approach will be to provide all the dmd versions as debian packages, same with most of the stuff in the dlang base image. This will give much more flexibility to matrix builds, because what would happen if at some point we want to also test different versions of ebtree to make sure they work with ocean? Or any other dependency? I think sooner or later this will happen and we can't provide any arbitrary combination of dependency versions as full docker images (like `dlang:dmd1.080-ebtree6.0.1-tangort1.7.0`, etc). If all dependencies are shipped as debian packages, then all we need is only one docker file (per distro anyway), just like we have now, but the matrix will be something like:

```yaml
env:
    - DC=dmd1-1.078.0 DIST=trusty F=production
    - DC=dmd1-1.078.0 DIST=trusty F=devel
    - DC=dmd1-1.080.0 DIST=xenial F=production
    - DC=dmd1-1.080.0 DIST=xenial F=devel
    # ...
```

 `docker/build` will be like:

```sh
# Install dependencies
apt-get update
apt-get install -y \
    # ...
    libgcrypt11-dev \
    libgpg-error-dev \
    $(echo $DC | tr -- - =)
```

and the `ci/ci.sh` script:

```sh
# ...
if echo "$DC" | grep -q '^dmd1'; then
	make -r d2conv
fi

export DC=$(echo "$DC" | cut -d- -f1)

make ...
```

The problem is where to store the packages? It occurred to me that one option could be the GitHub releases, but we don't want to create released for dmd1 for example and we don't have yet a repository for dmd-transitional (this probably has to change though). I thought of using GitHub pages, but with both these approaches we either can only serve the deb files, so we can't use `apt install` so we need to resolve dependencies manually, so probably going for a full apt repo is the best option.

I'm trying out https://bintray.com/ and it looks quite promising. It's a bit more complex than just a file storage but it looks indeed cool, associating packages with github releases, etc.

I will add more findings as I progress with this, but comments on the general design I'm envisioning are welcome!

**Comment by leandro-lucarella-sociomantic** [comment]
The `dlang` docker image can provide a default compiler for each of the series (dmd1, dmd-transitional, dmd) and the user can change this default as needed for matrix builds.

**Comment by mihails-strasuns-sociomantic** [comment]
Is creating public sociomantic PPA not an option?

**Comment by mihails-strasuns-sociomantic** [comment]
(for purely infrastructural usage, not dev machine usage)

**Comment by leandro-lucarella-sociomantic** [comment]
Not a practical one, as PPAs are really a mix of a deb repo and a build farm, so you have to upload source packages, you can't upload binary packages. To do that we'll need to convert all our packaging scripts to use standard debian tools instead of `fpm` (which is a bit overkill).

There is a [feature request to support PPAs](https://github.com/jordansissel/fpm/issues/170) in some way (for which `fpm` should basically generate a source package), but it doesn't look that it will be addressed soon.

**Comment by leandro-lucarella-sociomantic** [comment]
And actually I found out about bintray via that issue.

**Comment by mihails-strasuns-sociomantic** [comment]
> Not a practical one, as PPAs are really a mix of a deb repo and a build farm, so you have to upload source packages, you can't upload binary packages.

Didn't know that, your idea makes a lot of sense in that case.

**Comment by leandro-lucarella-sociomantic** [comment]
We are going for the packages approach.
