### ISSUE TITLE
Separate base and build-base images

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/cachalot#58]
Comes from https://github.com/sociomantic-tsunami/dhtnode/pull/136#discussion_r202753499 - current `base` image is a bit too "fat" for deployment purpose as it install bunch of tools used for development. The real base should simply add sociomantic bintray repos and GPG key and stop at that.

**Comment by leandro-lucarella-sociomantic** [comment]
Originally I thought of renaming `base` to `devel` and name the new image `base`, but the transition of places where `base` is used, even if probably just a few, might be annoying (with semver, by just making a new `base` major that is completely breaking, it would be doable though). Another option to keep it simpler would be to call the new image `deploy` or something.

**Comment by mihails-strasuns-sociomantic** [comment]
Would it be that annoying though? No one who care about breakage should use `latest`.

**Comment by leandro-lucarella-sociomantic** [comment]
Yes, I know, there is no risk of breakage (or the breakage is expected), It's just a non-conventional upgrade path, as you'll have to change the image name, not only the version.

**Comment by mihails-strasuns** [comment]
True, but `base` is just so much more reasonable name for thin minimal image used as base for everything else :) It would be weird to have `base` to depend on `deploy` otherwise.

**Comment by leandro-lucarella-sociomantic** [comment]
By looking at the images when adding bionic support, I also think we should move `ebtree` from the `dlang` bintray repo to its own.

**Comment by leandro-lucarella-sociomantic** [comment]
https://github.com/sociomantic-tsunami/ebtree/pull/20

**Comment by leandro-lucarella-sociomantic** [comment]
I think I will reassign to v6 so we can make the breaking changes.

**Comment by leandro-lucarella-sociomantic** [comment]
I tried with the approach of using `base` as the "base runtime" image and rename the old `base` to `devel` as the "base build" image, based on the new `base` image, but since I need to add bintray repos to the "base runtime" image, we get again into the chichen and the egg problem that to have packages in the repo when bootstrapping a new Ubuntu version, we need to build the packages and for that we need the image.

I think I will go for a `baseruntime` image and make it independent from the build images (current `base`). We can share some scripts to build them if necessary, but not build the "base build" image from the "base runtime" image.

Actually in terms of image development, the `baseruntime` images should be the last we can build when bootstrapping new Ubuntu versions.
